version: "3.9"
services:
  shared:
    image: "busybox"
    volumes:
      - "db:/var/lib/postgresql/data:cached"
      - "bundle:/usr/local/bundle:cached"
  db:
    image: postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
    volumes_from:
      - "shared"
    ports:
      - "5432:5432"
  rails: &app_base
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - ./.env.dev
    volumes:
      - .:/app:cached
    volumes_from:
      - "shared"
    ports:
      - "3000:3000"
    depends_on:
      - db    
    tty: true
    stdin_open: true
  solargraph:
    <<: *app_base  
    ports:
      - 7658:7658
    command: ["solargraph", "socket", "--host", "0.0.0.0", "--port", "7658"]
    restart: always
  webpacker:
    <<: *app_base  
    environment:
      - RAILS_ENV=development
      - NODE_ENV=development
      - "WEBPACKER_DEV_SERVER_HOST:webpacker"
    command: "bin/webpack-dev-server" 
    ports:
      - "3035:3035"
    tty: false
    stdin_open: false
    depends_on:
      - rails
volumes:
  db:
    driver: local
  bundle:
    driver: local
