FROM ruby:2.7.1

ENV LANG C.UTF-8
# 必要なのをインストール
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    libfontconfig1 && \
    rm -rf /var/lib/apt/lists/*
# nodeとyarnをインストール
RUN apt-get update -qq && apt-get install -y build-essential nodejs \
 && rm -rf /var/lib/apt/lists/* \
 && curl -o- -L https://yarnpkg.com/install.sh | bash

RUN mkdir /app
WORKDIR /app
COPY . /app
RUN bundle config build.nokogiri --use-system-libraries
# PORT設定
EXPOSE 3000
EXPOSE 7658

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
# Start the main process.
CMD ["rails", "server", "-b", "0.0.0.0"]

